events {}

http {
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/domain.crt;
        ssl_certificate_key /etc/nginx/certs/domain.key;

        location /domain1/ {
			proxy_pass http://app1:80/;
		}

        location /domain2/ {
			proxy_pass http://app2:80/;
		}
    }
}
